### PR TITLE
Fix ||| block parsing

### LINKED ISSUE #430: Fix ||| string parsing
||| string parsing had a lot of issues, from not supporting \r\n, to not successfully parsing something like

```
|||
foo
|||
``` 

(string content has the same indentation level as |||

### PR DESCRIPTION
**Pull request by stephenamar-db**
This PR fixes 2 edges cases that sjsonnet did not handle properly.

1. ||| blocks with \r\n
2. ||| blocks only with empty - indented - lines.

The only practical way I found to fix this is to half-rewrite the parsing code myself to better get a handle on how fastparse works.

This closes #430

### CODE REVIEW

File: sjsonnet/src/sjsonnet/Parser.scala [hunk 1]
```diff
@@ -160,18 +141,37 @@ class Parser(
...
+    case (true, lines) =>
+      Seq(lines.mkString.stripLineEnd)
+    case (false, lines) =>
+      lines
+  }
+
+  def tripleBarString[$: P]: P[(Boolean, Seq[String])] = P(
+    ("||-" | "||").!.map(_.last == '-')./ ~~ CharsWhileIn(" \t", 0) ~~
+    // Detect the new line separator
+    ("\r\n" | "\n").!.flatMapX { sep =>
```
Comment (He-Pin) [inline sjsonnet/src/sjsonnet/Parser.scala]: should we add a `/` after `.!`

File: sjsonnet/src/sjsonnet/Parser.scala [hunk 2]
```diff
@@ -160,18 +141,37 @@ class Parser(
...
+    case (true, lines) =>
+      Seq(lines.mkString.stripLineEnd)
+    case (false, lines) =>
+      lines
+  }
+
+  def tripleBarString[$: P]: P[(Boolean, Seq[String])] = P(
+    ("||-" | "||").!.map(_.last == '-')./ ~~ CharsWhileIn(" \t", 0) ~~
+    // Detect the new line separator
+    ("\r\n" | "\n").!./.flatMapX { sep =>
```
Comment (He-Pin) [inline sjsonnet/src/sjsonnet/Parser.scala]: if it fail, we should give an error message, the `text block must start with at least one whitespace` here

File: sjsonnet/test/src-jvm-native/sjsonnet/FileTests.scala [hunk 3]
```diff
@@ -4,7 +4,7 @@ import utest.*
 
 object FileTests extends BaseFileTests {
   val testDataSkippedTests: Set[String] = Set(
-    "dos_line_endings.jsonnet",
+//    "dos_line_endings.jsonnet",
```
Comment (He-Pin) [inline sjsonnet/test/src-jvm-native/sjsonnet/FileTests.scala]: Add A comment here , why we skip this tests?

File: sjsonnet/src/sjsonnet/Parser.scala [hunk 4]
```diff
@@ -160,18 +141,41 @@ class Parser(
...
+      lines.dropRight(1) ++ Seq(lines.last.stripLineEnd)
+    case (false, lines) =>
+      lines
+  }
+
+  def tripleBarString[$: P]: P[(Boolean, Seq[String])] = P(
+    ("||-" | "||").!.map(_.last == '-')./ ~~ CharsWhileIn(" \t", 0) ~~
+    // Detect the new line separator
+    ("\r\n" | "\n").opaque("|||-blocks require multiple lines").!./.flatMapX { sep =>
+      tripleBarStringLines(sep)
```
Comment (He-Pin) [inline sjsonnet/src/sjsonnet/Parser.scala]: this line can be just `tripleBarStringLines`?

File: sjsonnet/src/sjsonnet/Parser.scala [hunk 5]
```diff
@@ -160,18 +141,41 @@ class Parser(
...
+    } ~~ CharsWhileIn(" \t", 0) ~~ "|||"
```
Comment (He-Pin) [inline sjsonnet/src/sjsonnet/Parser.scala]: can be have `CharsWhileIn(" \t", 0)` and `CharsWhileIn(" \t", 1)` a val?

File: sjsonnet/test/src-jvm-native/sjsonnet/FileTests.scala (hunk 3 above)
Comment (He-Pin) [reply sjsonnet/test/src-jvm-native/sjsonnet/FileTests.scala]: The cpp jsonnet passes this test, not sure why this is skipped

Comment (stephenamar-db) [reply sjsonnet/test/src-jvm-native/sjsonnet/FileTests.scala]: not skipped anymore. that's the point of this PR.
