### PR TITLE
Disallow function values in std.format

### LINKED ISSUE #144: Inconsistency between sjsonnet and jsonnet
I happened to use jsonnet to compile Runbot's jsonnet file, which was failing but passed for sjsonnect.

The command I used:
```
/usr/local/Cellar/jsonnet/0.18.0/bin/jsonnet /Users/Lei.Wu/databricks/universe/ci/runbot/staging/runbot-app.jsonnet
```

and the error message from jsonnet is:
```
RUNTIME ERROR: couldn't manifest function in JSON output.
	std.jsonnet:36:49	function <anonymous>
	std.jsonnet:592:9-26	function <format_code>
	std.jsonnet:768:15-50	thunk <s>
	std.jsonnet:773:24	thunk <str>
	std.jsonnet:480:30-33
	std.jsonnet:480:19-34	thunk <w>
	std.jsonnet:476:11	thunk <w>
	std.jsonnet:472:12	function <aux>
	std.jsonnet:476:7-17	function <padding>
	std.jsonnet:480:7-38	function <pad_left>
	...
	std.jsonnet:774:11-60	function <format_codes_obj>
	std.jsonnet:774:11-60	function <format_codes_obj>
	std.jsonnet:779:7-43	function <anonymous>
	std.jsonnet:237:7-23	function <anonymous>
	/Users/Lei.Wu/databricks/universe/ci/runbot/staging/../builds/dust/utils.jsonnet.TEMPLATE:(168:5)-(188:6)	thunk <array_element>
	/Users/Lei.Wu/databricks/universe/ci/runbot/staging/../builds/dust/testshard-jobs.jsonnet.TEMPLATE:186:28-46	thunk <array_element>
	/Users/Lei.Wu/databricks/universe/ci/runbot/staging/../builds/dust/testshard-jobs.jsonnet.TEMPLATE:(185:22)-(189:6)	object <anonymous>
	/Users/Lei.Wu/databricks/universe/ci/runbot/staging/runbot-app.jsonnet.TEMPLATE:(187:5)-(203:6)	thunk <array_element>
	/Users/Lei.Wu/databricks/universe/ci/runbot/staging/runbot-app.jsonnet.TEMPLATE:(16:11)-(901:4)	object <anonymous>
	During manifestation
```

### PR DESCRIPTION
**Pull request by szeiger**
For compatibility with jsonnet. Fixes #144.

### CODE REVIEW

File: sjsonnet/test/src-jvm-native/sjsonnet/ErrorTests.scala [hunk 1]
```diff
@@ -289,28 +282,40 @@ object ErrorTests extends TestSuite{
...
       """|sjsonnet.Error: binding parameter a second time: x
          |    at [Apply].(sjsonnet/test/resources/imports/error.too_many_arg_with_named_arg.jsonnet:2:2)
-         |""".stripMargin
+         |""".stripMargin,
+      suite = "imports"
+    )
+
+    test("format_func") - check(
+      """|sjsonnet.Error: Cannot format function value
+         |    at [Function].(sjsonnet/test/resources/db/error.format_func.jsonnet:1:9)
```
Comment (szeiger) [inline sjsonnet/test/src-jvm-native/sjsonnet/ErrorTests.scala:315]: ...and unlike the C++ implementation we even produce a useful position that points the the failing argument

**Review by iuliand-db — APPROVED** [review]
