### PR TITLE
Fix multiple object comprehension bugs

### LINKED ISSUE #331: bug: defining functions in object comprehensions
refs: https://github.com/CertainLach/jrsonnet/issues/88
https://jsonnet.org/learning/tutorial.html#computed_field_names
https://jsonnet.org/learning/tutorial.html#comprehension

```jsonnet
local funcs = {
  [a](x): x * 2
  for a in ["f1", "f2", "f3"]
};
funcs.f1(10)
```

should gives:
```
20
```
, bug sjsonnet gives:

```
scala.MatchError: Field(Position((memory), 18),Dyn(Id a@Position((memory), 19)),false,Params([x], [null]),Normal,BinaryOp *@Position((memory), 28)) (of class sjsonnet.Expr$Member$Field)
	at sjsonnet.Parser.objinside(Parser.scala:385)
	at sjsonnet.Parser.expr2(Parser.scala:308)
	at sjsonnet.Parser.expr1(Parser.scala:248)
	at sjsonnet.Parser.expr(Parser.scala:185)
	at sjsonnet.Parser.bind(Parser.scala:432)
	at sjsonnet.Parser.parse0$3$1(Parser.scala:182)
	at sjsonnet.Parser.rec$9(Parser.scala:182)
	at sjsonnet.Parser.localExpr(Parser.scala:182)
	at sjsonnet.Parser.local(Parser.scala:271)
	at sjsonnet.Parser.expr2(Parser.scala:337)
	at sjsonnet.Parser.expr1(Parser.scala:248)
	at sjsonnet.Parser.expr(Parser.scala:185)
	at sjsonnet.Parser.document(Parser.scala:468)
	at sjsonnet.CachedResolver.$anonfun$2(Importer.scala:202)
	at fastparse.SharedPackageDefs.parseInputRaw(SharedPackageDefs.scala:69)
	at fastparse.SharedPackageDefs.parseInputRaw$(SharedPackageDefs.scala:6)
	at fastparse.package$.parseInputRaw(package.scala:5)
	at fastparse.SharedPackageDefs.parse$$anonfun$1(SharedPackageDefs.scala:35)
	at fastparse.ParserInputSource$fromParserInput.parseThrough(ParserInput.scala:25)
	at fastparse.SharedPackageDefs.parse(SharedPackageDefs.scala:42)
	at fastparse.SharedPackageDefs.parse$(SharedPackageDefs.scala:6)
	at fastparse.package$.parse(package.scala:5)
	at sjsonnet.CachedResolver.parse$$anonfun$1(Importer.scala:202)
```

it fails at this line:
```scala
      val Expr.Member.Field(offset, Expr.FieldName.Dyn(lhs), plus, null, Visibility.Normal, rhs) =
        exprs(preLocals.length): @unchecked
```

@JoshRosen @stephenamar-db cc

The funcs is something like:

```jsonnet
local funcs = {
  f1(x): x * 2,
  f2(x): x * 2,
  f3(x): x * 2
}
```

Change to ：
```
      val Expr.Member.Field(offset, Expr.FieldName.Dyn(lhs), plus, args, Visibility.Normal, rhs) =
        exprs(preLocals.length): @unchecked
```
the results become:

```scala
Unknown variable: x
    at [Id x].(:2:11)

```

### LINKED ISSUE #357: Evaluator.visitObjComp doesn't propagate context correctly
I wasn't yet able to fully root cause the issue but I derived a minimal example

main.jsonnet
```
local lib = import "libbroken.libsonnet";

{
  base:: {}
}
+ lib.foo()
```

libbroken.libsonnet
```
{
  foo()::
    {
      local global = self,

      [iterParam]: global.base {
        foo: iterParam
      }
      for iterParam in ["foo"]
    },
}
```

The issue seems to be specific to how the for loop (triggering `visitObjComp`) is handled. The output is generated properly when the lib code is replaced by

libworking.libsonnet
```
{
  foo()::
    {
      local global = self,

      foo: global.base {
        foo: "bar"
      }
    },
}
```

It also generates properly if the `global` variable is omitted and `self` is used directly.

### PR DESCRIPTION
**Pull request by JoshRosen**
This PR fixes multiple bugs in object comprehensions (fixes #357, fixes #331, plus another bug).

## Mis-handling of `self` and `super` in object comprehension locals when inherited

Object comprehensions may define local variables and those variables may reference `self` or `super`.

Consider the reproduction reported in https://github.com/databricks/sjsonnet/issues/357:

```jsonnet
local lib = {
  foo()::
    {
      local global = self,

      [iterParam]: global.base {
        foo: iterParam
      }
      for iterParam in ["foo"]
    },
};

{
 base:: {}
}
+ lib.foo()
```

This is supposed to output

```json
{
  "foo": {
    "foo": "foo"
  }
}
```

but sjsonnet outputs

```
sjsonnet.Error: Field does not exist: base
      at [Select base].(:7:26)
```

This bug occurs because of how bindings were managed: there's some tricky circular reference and variable rebinding logic (which I believe was added to handle references _between_ locals) and that was rebinding the `self` reference to the comprehension result itself: that is wrong because the `self` reference may change if an object is inherited or extended.

While digging into this, I also discovered a related bug where `super` wasn't being properly re-bound in object comprehension locals or values:

```jsonnet
local lib = {
  foo():: {
    local sx = super.x,
    [k]: sx + 1
    for k in ["x"]
  },
};

{ x: 2 }
+ lib.foo()
```

was failing with

```
java.lang.Exception: sjsonnet.Error: Attempt to use `super` when there is no super class
      at [SelectSuper x].(:4:21)
      at [ValidId sx].(:5:10)
      at [BinaryOp +].(:5:13)
```

## Silent dropping of fields if key is not a string

The object comprehension

```jsonnet
{[k]: k for k in [1]}
```

fails in regular jsonnet with an error

```
RUNTIME ERROR: field must be string, got: number
        <cmdline>:1:1-22
```

but in sjsonnet it was silently returning `{}`. This regression was [introduced](https://github.com/databricks/sjsonnet/pull/226/files#diff-7e786f55f42d493f85bfb37e5181c1c942ea039b21a307680e4e6913a8084aa2L628-R631) in #226 by adding a default `case _ =>` (presumably to fix a compiler or IDE warning).

## Support function definition via object comprehensions

This fixes https://github.com/databricks/sjsonnet/issues/331 by adding parser support for defining functions using method syntax, e.g.

```jsonnet
{
  [a](x): x * 2
  for a in ["f1", "f2", "f3"]
}
```

## Fixes

This PR fixes the above bugs by changing logic within `Evaluator.visitObjComp`. It is best reviewed commit-by-commit or using a whitespace-free diff.

### CODE REVIEW

File: sjsonnet/src/sjsonnet/Evaluator.scala [hunk 1]
```diff
@@ -841,42 +841,40 @@ class Evaluator(
   def visitObjComp(e: ObjBody.ObjComp, sup: Val.Obj)(implicit scope: ValScope): Val.Obj = {
     val binds = e.preLocals ++ e.postLocals
     val compScope: ValScope = scope // .clearSuper
-
-    lazy val newSelf: Val.Obj = {
```
Comment (JoshRosen) [inline sjsonnet/src/sjsonnet/Evaluator.scala:845]: Since `newSelf` was no longer referenced after other changes, I decided to remove it to simplify the code and to avoid the risk of future mis-use of it.

File: sjsonnet/src/sjsonnet/Evaluator.scala [hunk 2]
```diff
@@ -841,42 +841,40 @@ class Evaluator(
...
+    val builder = new java.util.LinkedHashMap[String, Val.Obj.Member]
+    for (s <- visitComp(e.first :: e.rest, Array(compScope))) {
+      visitExpr(e.key)(s) match {
+        case Val.Str(_, k) =>
+          val prev_length = builder.size()
+          builder.put(
+            k,
+            new Val.Obj.Member(e.plus, Visibility.Normal) {
+              def invoke(self: Val.Obj, sup: Val.Obj, fs: FileScope, ev: EvalScope): Val = {
+                lazy val newScope: ValScope = s.extend(newBindings, self, sup)
```
Comment (JoshRosen) [inline sjsonnet/src/sjsonnet/Evaluator.scala:853]: There are two changes here:

1. use `self` instead of `newSelf`, which allows for bindings' references to `self` to be properly updated when re-evaluated.
2. Pass in `sup` to allow `super` references to resolve properly.

File: sjsonnet/src/sjsonnet/Evaluator.scala [hunk 3]
```diff
@@ -841,42 +841,40 @@ class Evaluator(
...
+                lazy val newBindings = visitBindings(binds, (self, sup) => newScope)
+                visitExpr(e.value)(
+                  s.extend(newBindings, self, null)
```
Comment (JoshRosen) [inline sjsonnet/src/sjsonnet/Evaluator.scala:856]: On closer look, I see that this is still passing `null` for `newSuper` here and that probably indicates that there's still a latent bug. Let me see if I can devise a test case.

Comment (JoshRosen) [reply sjsonnet/src/sjsonnet/Evaluator.scala]: Indeed:

- Test: https://github.com/databricks/sjsonnet/pull/358/commits/55bcb2684a39a386981cb1f5ded712a92dcc3f82
- Fix: https://github.com/databricks/sjsonnet/pull/358/commits/fd038d84823f521c6213435730dcd373a7add26a

**Comment by JoshRosen** [comment]
I noticed that `ValScope.extend` and `Evaluator.visitBindings` now each only have a single callsite, which might permit some further simplification.

**Comment by He-Pin** [comment]
https://github.com/databricks/sjsonnet/issues/331

@JoshRosen Does this fix #331 too?

File: sjsonnet/src/sjsonnet/Evaluator.scala [hunk 4]
```diff
@@ -841,42 +837,38 @@ class Evaluator(
...
-        new java.util.HashMap[Any, Val]()
+          )
+          if (prev_length == builder.size() && settings.noDuplicateKeysInComprehension) {
+            Error.fail(s"Duplicate key ${k} in evaluated object comprehension.", e.pos);
+          }
+        case Val.Null(_) => // do nothing
+        case x =>
+          Error.fail(
+            s"Field name must be string or null, not ${x.prettyName}",
+            e.pos
```
Comment (He-Pin) [inline sjsonnet/src/sjsonnet/Evaluator.scala:862]: `Field name must be string or null, got ${x.prettyName}`

File: sjsonnet/src/sjsonnet/ValScope.scala [hunk 5]
```diff
@@ -18,23 +18,11 @@ final class ValScope private (val bindings: Array[Lazy]) extends AnyVal {
...
   def length: Int = bindings.length
 
-  def extend(
-      newBindingsF: Array[(Val.Obj, Val.Obj) => Lazy] = null,
-      newSelf: Val.Obj,
-      newSuper: Val.Obj): ValScope = {
-    val by = if (newBindingsF == null) 2 else newBindingsF.length + 2
-    val b = Arrays.copyOf(bindings, bindings.length + by)
+  def extend(newBindings: Array[Lazy], newSelf: Val.Obj, newSuper: Val.Obj): ValScope = {
+    val b = Arrays.copyOf(bindings, bindings.length + newBindings.length + 2)
```
Comment (He-Pin) [inline sjsonnet/src/sjsonnet/ValScope.scala:22]: bindings.length and newbindings.length can be extracted to a local variable?

File: sjsonnet/src/sjsonnet/Evaluator.scala [hunk 6]
```diff
@@ -841,42 +837,38 @@ class Evaluator(
...
+    for (s <- visitComp(e.first :: e.rest, Array(compScope))) {
+      visitExpr(e.key)(s) match {
+        case Val.Str(_, k) =>
+          val prev_length = builder.size()
+          builder.put(
+            k,
+            new Val.Obj.Member(e.plus, Visibility.Normal) {
+              def invoke(self: Val.Obj, sup: Val.Obj, fs: FileScope, ev: EvalScope): Val = {
+                lazy val newScope: ValScope = s.extend(newBindings, self, sup)
+                lazy val newBindings = visitBindings(binds, newScope)
```
Comment (He-Pin) [inline sjsonnet/src/sjsonnet/Evaluator.scala:850]: This code is a little weird, it references each other

File: sjsonnet/src/sjsonnet/Evaluator.scala (hunk 4 above)
Comment (JoshRosen) [reply sjsonnet/src/sjsonnet/Evaluator.scala:862]: I copied this wording from https://github.com/databricks/sjsonnet/blob/84ac3207d3b615ce887b5b99263f143655f60487/sjsonnet/src/sjsonnet/Evaluator.scala#L683-L687 further up in this file; I suppose I can factor it out into a helper function.

File: sjsonnet/src/sjsonnet/ValScope.scala (hunk 5 above)
Comment (JoshRosen) [reply sjsonnet/src/sjsonnet/ValScope.scala:22]: I would prefer to leave this as-is for now, given that the other methods (including `extendSimple`) have similar repetition of `.length`. My understanding is that JIT should already be optimizing this nicely.

File: sjsonnet/src/sjsonnet/Evaluator.scala (hunk 4 above)
Comment (JoshRosen) [reply sjsonnet/src/sjsonnet/Evaluator.scala]: I factored this out in bd4e1b2fb2efe578cf2b3277d4c5806e79cc0263 but, curiously, this appears to cause a test failure in the JDK 17 build: https://github.com/databricks/sjsonnet/actions/runs/14891478275/job/41824335648 :

```
java.lang.StackOverflowError
    java.lang.String.rangeCheck(String.java:304)
    java.lang.String.<init>(String.java:300)
    jdk.internal.org.objectweb.asm.ClassReader.readUtf(ClassReader.java:3717)
    jdk.internal.org.objectweb.asm.ClassReader.readUtf(ClassReader.java:3685)
    jdk.internal.org.objectweb.asm.ClassReader.readUTF8(ClassReader.java:3666)
    jdk.internal.org.objectweb.asm.ClassReader.readConst(ClassReader.java:3841)
    java.lang.invoke.MethodHandles$Lookup$ClassFile.newInstance(MethodHandles.java:2258)
    java.lang.invoke.MethodHandles$Lookup.makeHiddenClassDefiner(MethodHandles.java:2359)
    java.lang.invoke.MethodHandles$Lookup.defineHiddenClass(MethodHandles.java:2127)
    java.lang.invoke.InnerClassLambdaMetafactory.generateInnerClass(InnerClassLambdaMetafactory.java:407)
    java.lang.invoke.InnerClassLambdaMetafactory.spinInnerClass(InnerClassLambdaMetafactory.java:315)
    java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:228)
    java.lang.invoke.LambdaMetafactory.altMetafactory(LambdaMetafactory.java:536)
    java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:147)
    java.lang.invoke.CallSite.makeSite(CallSite.java:315)
    java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)
    java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)
    os.Path.relativeTo(Path.scala:584)
    sjsonnet.OsPath.relativeToString(OsPath.scala:6)
    sjsonnet.Error$Frame.<init>(Error.scala:51)
    sjsonnet.Error$.fail(Error.scala:71)
    sjsonnet.Materializer.apply0(Materializer.scala:72)
    sjsonnet.Materializer.apply0(Materializer.scala:53)
    sjsonnet.Materializer.apply0(Materializer.scala:53)
[...]
```

I think the problem is that we have code within the `Materializer` which catches `StackOverflowError` and then tries to call `Error.fail` and that, in turn, hits a secondary `StackOverflow` because the stack is already so deep:

https://github.com/databricks/sjsonnet/blob/84ac3207d3b615ce887b5b99263f143655f60487/sjsonnet/src/sjsonnet/Materializer.scala#L70-L73

I tried adding an `@inline` to the new helper to see if that would somehow hack around this (https://github.com/databricks/sjsonnet/pull/358/commits/f5e40c2b8e172825438e396f1cc5ee5577dc20ad) but it didn't help.

This preexisting design seems very fragile.

If we want to more fundamentally fix this and remove the core fragility, I think we probably need to allow the `StackOverflowError` to bubble higher rather than catching it so deep, but that introduces some new challenges around making sure that we preserve the `v` which triggered the error. I'm thinking that we might want to re-throw a wrapped exception containing a pointer to `v` and then catch it and transform it to an `Error.fail` at a higher level of the callstack (e.g. the outermost `apply0` call). That's a larger refactoring / change, though, and I don't want to co-mingle it here.

Given this, I'm going to back out of the error message DRY and will re-attempt it in a separate PR.

**Comment by JoshRosen** [comment]
> #331
> 
> I tested with
> 
> ```scala
>       eval(
>         """
>           |local funcs = {
>           |  [a](x): x * 2
>           |  for a in ["f1", "f2", "f3"]
>           |};
>           |funcs.f1(10)
>           |""".stripMargin) ==> ujson.Num(20)
> ```
> 
> gets:
> 
> ```
> sjsonnet.StaticError: Unknown variable: x
>     at [Id x].(:3:11)
> 
> java.lang.Exception: sjsonnet.StaticError: Unknown variable: x
>     at [Id x].(:3:11)
> ```

I think more / different work is needed to support this: that `StaticError` is being thrown before we even begin evaluation, so it's not even hitting any of the `Evaluator` code modified in this PR.

As you noted in https://github.com/databricks/sjsonnet/pull/337, the problem is that we're currently discarding any knowledge of RHS args (denoting that it's a function).

This turned out to be fairly straightforward to fix: I just needed to modify the parser to create an `Expr.Function` when `args` are present: e06e7a7fc286ae4b8b5590cd654715a5124f7364 ; I'll update the PR description to reflect this fix.

File: sjsonnet/src/sjsonnet/Evaluator.scala (hunk 4 above)
Comment (JoshRosen) [reply sjsonnet/src/sjsonnet/Evaluator.scala]: I think that this is a test ordering issue: the current test for the stack overflow handling fails if it runs prior to other tests: it was implicitly relying on other tests to perform certain loading and initialization steps.

We should fix this properly (e.g. by hardening the actual implementation, as this is a real bug), but as a temporary "unblock the test flakiness" hack I'm trying to force a particular loading step: 5cd4ed8dbd321561ce4583762f11cda407aa5c4f

Comment (He-Pin) [reply sjsonnet/src/sjsonnet/Evaluator.scala]: `@inline` is just a hint; we can't rely on it.
For StackOverflow, I raised https://github.com/databricks/sjsonnet/issues/284 once, but it may hurt some performance; there is some TCO in other implementations.

**Comment by anujpunekar20** [comment]
hi

**Review by stephenamar-db — APPROVED** [review]

**Comment by stephenamar-db** [comment]
Thanks @JoshRosen

**Comment by He-Pin** [comment]
@JoshRosen Thank you , helps a lot
